version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${API_PORT}:8000"
    command: "uvicorn --factory app.application.api.main:create_app --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ..:/app/